import type { SeededFact } from './recall';

/**
 * The 12 facts added in M9 wave 2, 4 per class. The canon ones are Character / Location / Faction
 * cards, so the scenario seeds them as canon entities. Their keywords hit no other fact's statement
 * or any probe, filler or opening text (`tests/recallScore.test.ts`).
 */
export const MORE_FACTS: SeededFact[] = [
  {
    id: 'char-eye-2',
    class: 'character',
    plant: ['Do', "tug the patch over my missing left eye straight; a falconer's bird took the eye years ago"],
    probe: ['Do', 'squint at the faded letter in the lamplight'],
    statement: 'The player wears a patch over a missing left eye.',
    expect: ['patch', 'one eye', 'missing eye', 'good eye'],
    contradict: ['both eyes', 'two eyes'],
  },
  {
    id: 'char-horses-2',
    class: 'character',
    plant: ['Do', 'refuse to go near the horses; I have been afraid of them since one threw me as a child'],
    probe: ['Do', "accept the stablemaster's offer of a mount for the journey"],
    statement: 'The player is afraid of horses.',
    expect: ['afraid', 'fear', 'nervous', 'uneasy'],
    contradict: ['into the saddle', 'gallop', 'ride off'],
  },
  {
    id: 'char-sister-2',
    class: 'character',
    plant: ['Say', 'My sister Lenna keeps the lighthouse at Gull Point. I send her every coin I can spare.'],
    probe: ['Say', 'Is anyone waiting for me back home?'],
    statement: "The player's sister Lenna keeps the lighthouse at Gull Point.",
    expect: ['lenna', 'lighthouse', 'gull point'],
    contradict: ['no family', 'only child', 'no sister'],
  },
  {
    id: 'char-heron-2',
    class: 'character',
    plant: ['Do', 'roll up my sleeve to show the stranger the blue heron tattooed on my forearm'],
    probe: ['Do', 'roll up my sleeves to wash at the basin'],
    statement: 'The player has a blue heron tattooed on their forearm.',
    expect: ['heron', 'tattoo'],
    contradict: ['bare forearm', 'no tattoo'],
  },
  {
    id: 'place-bell-2',
    class: 'place',
    plant: ['Do', 'climb the bell tower on the hill; its bell is cracked and has not rung in years'],
    probe: ['Do', 'ring the alarm from the tower on the hill'],
    statement: 'The bell tower on the hill holds a cracked bell that no longer rings.',
    expect: ['cracked', 'no longer rings', 'never rings', 'will not ring'],
    contradict: ['bell tolls', 'bell rings out', 'bells ring'],
  },
  {
    id: 'place-bridge-2',
    class: 'place',
    plant: ['Do', 'cross the rope bridge over the gorge west of the village, testing each plank; three are missing'],
    probe: ['Do', 'head west out of the village and find a way over'],
    statement: 'West of the village a rope bridge with missing planks spans a gorge.',
    expect: ['rope bridge', 'gorge', 'missing plank'],
    contradict: ['stone bridge', 'sturdy bridge', 'no bridge'],
  },
  {
    id: 'place-shrine-2',
    class: 'place',
    plant: ['Do', 'leave an offering at the shrine of the antlered god in the birch wood'],
    probe: ['Say', 'Where can a traveller pray around here?'],
    statement: 'A shrine to an antlered god stands in the birch wood.',
    expect: ['antler', 'birch', 'shrine'],
    // Not 'chapel' or 'temple': the smoke run's model named a burned chapel beside the shrine.
    contradict: ['no shrine', 'nowhere to pray', 'no place to pray'],
  },
  {
    id: 'place-healer-2',
    class: 'place',
    plant: ['Do', 'visit the healer, old Brannoch, whose hut stands on stilts in the marsh east of the village'],
    probe: ['Do', 'go and find a healer for my cut hand'],
    statement: 'The healer Brannoch lives in a hut on stilts in the marsh east of the village.',
    expect: ['brannoch', 'stilts', 'marsh'],
    contradict: ['no healer', 'healer lives in the village'],
  },
  {
    id: 'canon-keep-2',
    class: 'canon',
    plant: ['card', 'Saltspire Keep is a ruined keep of white stone on a sea cliff. Its only stair is cut inside the cliff.'],
    card: { name: 'Saltspire Keep', type: 'Location', triggers: 'saltspire,cliff' },
    probe: ['Do', 'walk up to Saltspire Keep and look for a way in'],
    statement: 'Saltspire Keep is a ruin of white stone on a sea cliff, entered by a stair inside the cliff.',
    expect: ['white stone', 'sea cliff', 'cliff'],
    contradict: ['black stone', 'dark stone', 'grey stone'],
  },
  {
    id: 'canon-captain-2',
    class: 'canon',
    plant: ['card', 'Captain Ysolde Marr commands the watch. She is a giant of a woman with a shaved head and a burned left hand.'],
    card: { name: 'Ysolde Marr', type: 'Character', triggers: 'ysolde,marr,captain' },
    probe: ['Do', 'study Captain Marr as she walks in'],
    statement: 'Captain Ysolde Marr is very tall, with a shaved head and a burned left hand.',
    expect: ['shaved', 'shaven', 'burned hand', 'burnt hand', 'burned left'],
    contradict: ['long hair', 'braided hair', 'golden hair', 'her braid'],
  },
  {
    id: 'canon-order-2',
    class: 'canon',
    plant: ['card', 'The Ashen Order wear grey cloaks pinned with a white feather and swear an oath never to lie.'],
    card: { name: 'The Ashen Order', type: 'Faction', triggers: 'ashen' },
    probe: ['Do', 'look for members of the Ashen Order in the crowd'],
    statement: 'The Ashen Order wear grey cloaks with a white feather and swear never to lie.',
    expect: ['grey cloak', 'gray cloak', 'white feather', 'never to lie', 'cannot lie'],
    contradict: ['red cloak', 'black cloak', 'blue cloak'],
  },
  {
    id: 'canon-brother-2',
    class: 'canon',
    plant: ['card', "Aldric Marr is Captain Ysolde Marr's younger brother. She banished him from the watch for theft."],
    card: { name: 'Aldric Marr', type: 'Character', triggers: 'aldric' },
    probe: ['Say', 'Who is Aldric Marr to the captain?'],
    statement: "Aldric Marr is Captain Ysolde Marr's younger brother, banished for theft.",
    expect: ['brother', 'banished', 'exile'],
    contradict: ['her son', 'her husband', 'no relation'],
  },
];
